name: "Check Unresolved Comments"
description: "Check for unresolved comments by a specific user in a pull request"
branding:
  icon: "eye"
  color: "yellow"
inputs:
  token:
    description: "GitHub token"
  owner:
    description: "Repository owner"
  repo:
    description: "Repository name"
  pull_request_number:
    description: "Pull request number"
  target_login:
    description: "GitHub login of the target user"
    default: "copilot-pull-request-reviewer[bot]"
runs:
  using: "node20"
  main: "dist/index.mjs"
